spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: XXXXX

server:
  port: 8080

actable:
  table:
    auto: update
  model:
    pack: com.example.entity
  database:
    type: mysql